# Generated by Django 3.2.4 on 2021-07-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
