# Generated by Django 3.2.4 on 2021-07-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
