# Generated by Django 3.2.4 on 2021-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210705_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
