# Generated by Django 3.2.4 on 2021-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_phone_number_message_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
